brokerHost: pkc-4nym6.us-east-1.aws.confluent.cloud:9092
tls: true
image: alexellis/kafka-connector-pro:0.6.0-rc3-13-gaefea6a-amd64

saslAuth: true

replicas: 3

topics: "pipeline.subscription"

# Print the data read from the Kafka topic before invoking functions
printRequestBody: false

# Print the HTTP status of invoked functions
printResponse: true

# Print the data received from invoked functions
printResponseBody: false

initialOffset: newest

sessionLogging: true
