image: openfaas/kafka-connector:0.4.0
replicas: 1

# Max timeout for a function
upstreamTimeout: 2m

# Use with slow consumers or long running functions
asyncInvocation: false

# Alter to the topics required
topics: faas-request

# Your Kafka broker
brokerHost: kafka:9092

printResponse: true
printResponseBody: false

# Internal gateway URL
gatewayURL: http://gateway.openfaas:8080

# Basic auth for the gateway
basicAuth: true

nodeSelector: {}

tolerations: []

affinity: {}
